Profile page updated with basic logic
Gigacrew/DreamJournal-Android pull request #6
Opened 2023-08-03 14:33 UTC by JadeDevilakaJD

2023-08-03 17:46 UTC, Rahnken requested changes
As Mentioned , will need the layout file pushed up but this was a good start, once that layout file is up ping me on Discord and I'll finish the review. The project should have viewbinding set up if you want to use it , otherwise the way you have done things for now is fine

2023-08-03 17:46 UTC, Rahnken commented on app/src/main/java/com/gigacrew/dreamjournal/Login.kt
Login Layout File wasn't added to the commit, will need that before we can finalize this merge

2023-08-03 17:46 UTC, Rahnken commented on app/src/main/java/com/gigacrew/dreamjournal/Login.kt
> +            if (isValidCredentials(username, password)) {
This will need to be updated when dashboard page is finished

2023-08-07 02:50 UTC, JadeDevilakaJD commented on app/src/main/java/com/gigacrew/dreamjournal/Login.kt
added the layout file, it might be a mistake in committing or in pushing it to git, sorry for it and thanks to enlighten me.

2023-08-07 18:26 UTC, Rahnken approved these changes
Looks okay , I think the images on the OAuth buttons might be a little large, but its fine for now, should be okay. We'll also have to make sure to update the Manifest properly once all the screens are added but we can do that in another PR

2023-08-07 18:26 UTC, merged